<div class="contact">

    <div class="container">
        <h1>Контакты</h1>
        <h2 align="center" id="flash"><?=\Library\Session::getFlash()?></h2>
        <script>
            function check() {
                var username = document.getElementById('username');
                var email = document.getElementById('email');
                var message = document.getElementById('message');
                var flash = document.getElementById('flash');

                var res = username.value != '' && email.value != '' && message.value != '';

                if (!res) {
                    flash.innerHTML = 'Заполните все поля';
                }
                return res;

            }
        </script>
        <div class="contact-form">
            <div class="col-md-8 contact-grid">
                <form method="post" onsubmit="return check()">
                    <input id="username" type="text" name="username" value="<?=$form->username?>" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='Имя';}">

                    <input id="email" type="email" name="email" value="<?=$form->email?>" onfocus="this.value='';" onblur="if (this.value == '') {this.value ='Email';}">

                    <textarea id="message" name="message" cols="77" rows="6"  onfocus="this.value='';" onblur="if (this.value == '') {this.value = 'Сообщение';}"><?=$form->message?></textarea>
                    <div class="send">
                        <input type="submit" value="Отправить">
                    </div>
                </form>
            </div>
            <div class="col-md-4 contact-in">

                <div class="address-more">
                    <h4>Адрес</h4>
                    <p>Liza</p>
                    <p>Украина</p>
                    <p>г. Киев, ул. Т. Шамрыло, 6-а, офис 510</p>
                </div>
                <div class="address-more">
                    <h4>Контакты</h4>
                    <p>Тел: 063-123-45-67</p>
                    <p>Факс: 190-4509-494</p>
                    <p>Email:<a href="mailto:contact@example.com"> liza.kiev@mail.ru</a></p>
                </div>

            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37494223.23909492!2d103!3d55!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x453c569a896724fb%3A0x1409fdf86611f613!2sRussia!5e0!3m2!1sen!2sin!4v1415776049771"></iframe>
        </div>
    </div>
