
<div class="banner">
    <div class="container">
        <script src="/js/responsiveslides.min.js"></script>
        <script>
            $(function () {
                $("#slider").responsiveSlides({
                    auto: true,
                    nav: true,
                    speed: 500,
                    namespace: "callbacks",
                    pager: true,
                });
            });
        </script>
        <div  id="top" class="callbacks_container">
            <ul class="rslides" id="slider">
                <li>

                    <div class="banner-text">
                        <h3>Lorem Ipsum is not simply dummy  </h3>
                        <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor .</p>
                        <a href="single.html">Learn More</a>
                    </div>

                </li>
                <li>

                    <div class="banner-text">
                        <h3>There are many variations </h3>
                        <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor .</p>
                        <a href="single.html">Learn More</a>

                    </div>

                </li>
                <li>
                    <div class="banner-text">
                        <h3>Sed ut perspiciatis unde omnis</h3>
                        <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor .</p>
                        <a href="single.html">Learn More</a>

                    </div>

                </li>
            </ul>
        </div>

    </div>
</div>
<div class="container">
    <!----->

    <div class="content-top-bottom"><br>
        <h2>Избранные коллекции</h2>
        <div class="col-md-6 men">
            <a href="/clothesdetails-1.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="images/t1.jpg" alt="">
                <div class="b-wrapper">
                    <h3 class="b-animate b-from-top top-in b-delay03 ">
                        <span>Lorem</span>
                    </h3>
                </div>
            </a>


        </div>
        <div class="col-md-6">
            <div class="col-md1 ">
                <a href="/clothesdetails-2.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="images/t2.jpg" alt="">
                    <div class="b-wrapper">
                        <h3 class="b-animate b-from-top top-in1   b-delay03 ">
                            <span>Lorem</span>
                        </h3>
                    </div>
                </a>

            </div>
            <div class="col-md2">
                <div class="col-md-6 men1">
                    <a href="/clothesdetails-3.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="images/t3.jpg" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-top top-in2   b-delay03 ">
                                <span>Lorem</span>
                            </h3>
                        </div>
                    </a>

                </div>
                <div class="col-md-6 men2">
                    <a href="single.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="images/t4.jpg" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-top top-in2   b-delay03 ">
                                <span>Lorem</span>
                            </h3>
                        </div>
                    </a>

                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>