
<div class="container">
    <div class="account">
        <h1>Авторизация</h1>
        <h2 align="center"><?=\Library\Session::getFlash()?></h2>
        <div class="account-pass">
            <div class="col-md-8 account-top">
                <form method="post">
                    <div>
                        <span>Email</span>
                        <input type="email" placeholder="Email адрес" value="<?=$form->email?>" name="email"><br>
                    </div>
                    <div>
                        <span >Пароль</span>
                        <input type="password" placeholder="Ваш пароль" name="password"><br>
                        <input type="checkbox" name="remember"/> Remember me <br/>
                    </div>
                    <input type="submit" value="Войти">
                </form>
            </div>
            <div class="col-md-4 left-account ">
                <a href="/clothesdetails-1.html"><img class="img-responsive " src="images/s1.jpg" alt=""></a>
                <div class="five">
                    <h2>25% </h2><span>discount</span>
                </div>
                <a href="/registration" class="create">Зарегистрироватся</a>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
