<div class="product">
    <div class="container">
        <div class="col-md-3 product-price">
            <!--initiate accordion-->
            <script type="text/javascript">
                $(function() {
                    var menu_ul = $('.menu > li > ul'),
                        menu_a  = $('.menu > li > a');
                    menu_ul.hide();
                    menu_a.click(function(e) {
                        e.preventDefault();
                        if(!$(this).hasClass('active')) {
                            menu_a.removeClass('active');
                            menu_ul.filter(':visible').slideUp('normal');
                            $(this).addClass('active').next().stop(true,true).slideDown('normal');
                        } else {
                            $(this).removeClass('active');
                            $(this).next().stop(true,true).slideUp('normal');
                        }
                    });

                });
            </script>
        </div>
        <div class="col-md-9 product-price1">
            <div class="col-md-5 single-top">
                <div class="flexslider">
                        <div class="product-at2">
                            <a href="/cart?action=add&id=<?=$clothes['id']?>"><img class="img-responsive" src="/images/clothes/<?=$clothes['id']?>.jpg" alt="">
                            </a>
                        </div>

                </div>

            </div>
            <div class="col-md-7 single-top-in simpleCart_shelfItem">
                <div class="single-para ">
                    <h4><?=$clothes['title']?></h4>
                    <h5 class="item_price"><?=$clothes['price']?></h5>
                    <p><?=$clothes['description']?></p>
                    <a href="/cart?action=add&id=<?=$clothes['id']?>" class="add-cart item_add">Добавить в корзину</a>
                </div>
            </div>
            <div class="clearfix"> </div>
            <!---->
        <div class="clearfix"> </div>
    </div>
</div>
<div class="starter-template clothes-item cloth">
